services:
  - type: web
    name: resume-analyzer
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn run:app"
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        value: your-secret-key
      - key: DATABASE_URL
        fromDatabase:
          name: resume-analyzer-db
          property: connectionString

databases:
  - name: resume-analyzer-db
    plan: free
